env:
  RUBY_VERSION: 2.7.2
  map_quest_key: 'Tlozaze717aNRgdqhG8LSe8xRGhN6TQM'
  weather_key: 'b84b156e4bd181e2ee6502abc67b3257'
  image_key: 'bbb9a195543278ecbd127c1ab4ac7bdf'
@@ -36,9 +35,7 @@ jobs:
        uses: actions/checkout@v2
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
      - name: Install Gems
        run: bundle
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:migrate
      # Add or replace test runners here
      - name: Run tests
        run: rspec
